# Generated by Django 5.2.11 on 2026-02-14 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255, unique=True, verbose_name='اسم المجموعة')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود المجموعة')),
                ('is_mobile_group', models.BooleanField(default=False, verbose_name='مجموعة موبايل')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('django_group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecr_group', to='auth.group', verbose_name='مجموعة Django')),
            ],
            options={
                'verbose_name': 'مجموعة',
                'verbose_name_plural': 'المجموعات',
                'ordering': ['name_ar'],
            },
        ),
    ]
