# Generated by ChatGPT for ECR (CAD Reports)

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("regions", "0002_seed_regions"),
        ("organizations", "0001_initial"),
        ("usergroups", "0003_add_data_scope"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, unique=True, verbose_name="اسم نوع الحالة")),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّل")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="آخر تحديث")),
            ],
            options={
                "verbose_name": "نوع حالة (CAD)",
                "verbose_name_plural": "كتلوج أنواع الحالات (CAD)",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CADReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "cad_number",
                    models.CharField(
                        db_index=True,
                        help_text="رقم البلاغ في نظام CAD",
                        max_length=50,
                        unique=True,
                        verbose_name="رقم البلاغ CAD",
                    ),
                ),
                ("injured_count", models.PositiveIntegerField(default=0, verbose_name="عدد المصابين")),
                (
                    "severity",
                    models.CharField(
                        choices=[("simple", "بسيطة"), ("medium", "متوسطة"), ("critical", "حرجة")],
                        db_index=True,
                        default="medium",
                        max_length=20,
                        verbose_name="درجة الخطورة",
                    ),
                ),
                ("age", models.PositiveIntegerField(blank=True, null=True, verbose_name="العمر")),
                ("is_conscious", models.BooleanField(default=True, verbose_name="واعي؟")),
                ("details", models.TextField(blank=True, verbose_name="تفاصيل البلاغ")),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name="خط العرض")),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name="خط الطول")),
                (
                    "location_text",
                    models.CharField(
                        blank=True,
                        help_text="اختياري: عنوان/وصف نصي للموقع",
                        max_length=255,
                        verbose_name="وصف الموقع",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="وقت إنشاء البلاغ")),
                ("dispatched_at", models.DateTimeField(blank=True, null=True, verbose_name="وقت الترحيل")),
                ("accepted_at", models.DateTimeField(blank=True, null=True, verbose_name="وقت قبول المستجيب")),
                ("arrived_at", models.DateTimeField(blank=True, null=True, verbose_name="وقت الوصول")),
                ("time_to_dispatch", models.DurationField(blank=True, null=True, verbose_name="الزمن حتى الترحيل")),
                ("time_to_accept", models.DurationField(blank=True, null=True, verbose_name="الزمن حتى القبول")),
                ("time_to_arrive", models.DurationField(blank=True, null=True, verbose_name="الزمن حتى الوصول")),
                ("total_response_time", models.DurationField(blank=True, null=True, verbose_name="إجمالي زمن الاستجابة")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="آخر تحديث")),
                (
                    "case_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="cad_reports.casetype",
                        verbose_name="نوع الحالة",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cad_created_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="منشئ البلاغ (المرحل)",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cad_reports",
                        to="regions.region",
                        verbose_name="المنطقة",
                    ),
                ),
            ],
            options={
                "verbose_name": "بلاغ CAD",
                "verbose_name_plural": "بلاغات CAD",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_create_cad_report", "يمكنه إنشاء بلاغ CAD"),
                    ("can_dispatch_cad_report", "يمكنه ترحيل بلاغ CAD"),
                    ("can_accept_cad_report", "يمكنه قبول بلاغ CAD"),
                    ("can_mark_arrived_cad_report", "يمكنه تسجيل الوصول لبلاغ CAD"),
                    ("can_view_cad_report", "يمكنه عرض بلاغات CAD"),
                ],
            },
        ),
    ]
