# Generated by Django 5.2.11 on 2026-02-14 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadreport',
            name='cad_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='رقم البلاغ يجب أن يكون أرقام فقط', regex='^\\d+$')], verbose_name='رقم البلاغ CAD'),
        ),
    ]
