# Generated by Django 5.2.11 on 2026-02-15 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cad_reports', '0004_cadreport_close_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadreport',
            options={'ordering': ['-created_at'], 'permissions': [('can_create_cad_report', 'يمكنه إنشاء بلاغ CAD'), ('can_dispatch_cad_report', 'يمكنه ترحيل بلاغ CAD'), ('can_accept_cad_report', 'يمكنه قبول بلاغ CAD'), ('can_mark_arrived_cad_report', 'يمكنه تسجيل الوصول لبلاغ CAD'), ('can_close_cad_report', 'يمكنه إغلاق بلاغ CAD'), ('can_view_cad_report', 'يمكنه عرض بلاغات CAD')], 'verbose_name': 'بلاغ CAD', 'verbose_name_plural': 'بلاغات CAD'},
        ),
    ]
