# Generated by ChatGPT on 2026-02-17
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cad_reports", "0006_cadreporthistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cadreport",
            name="dispatched_source",
            field=models.CharField(
                choices=[("unknown", "غير محدد"), ("mobile", "تطبيق المستجيب"), ("web_manual", "يدوي (لوحة الوِب)")],
                default="web_manual",
                max_length=20,
                verbose_name="مصدر وقت الترحيل",
            ),
        ),
        migrations.AddField(
            model_name="cadreport",
            name="accepted_source",
            field=models.CharField(
                choices=[("unknown", "غير محدد"), ("mobile", "تطبيق المستجيب"), ("web_manual", "يدوي (لوحة الوِب)")],
                default="unknown",
                max_length=20,
                verbose_name="مصدر وقت القبول",
            ),
        ),
        migrations.AddField(
            model_name="cadreport",
            name="arrived_source",
            field=models.CharField(
                choices=[("unknown", "غير محدد"), ("mobile", "تطبيق المستجيب"), ("web_manual", "يدوي (لوحة الوِب)")],
                default="unknown",
                max_length=20,
                verbose_name="مصدر وقت الوصول",
            ),
        ),
        migrations.AddField(
            model_name="cadreport",
            name="accepted_set_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cad_accepted_set_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم تسجيل القبول بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="cadreport",
            name="arrived_set_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cad_arrived_set_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم تسجيل الوصول بواسطة",
            ),
        ),
    ]
