# Generated by Django 5.2.11 on 2026-02-17 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_reports', '0007_cadreport_time_sources'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadreport',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cad_created_reports', to=settings.AUTH_USER_MODEL, verbose_name='المرحل'),
        ),
        migrations.DeleteModel(
            name='CADReportHistory',
        ),
    ]
