# Generated by Django 5.2.11 on 2026-02-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_reports', '0008_alter_cadreport_created_by_delete_cadreporthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadreport',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=18, null=True, verbose_name='خط العرض'),
        ),
        migrations.AlterField(
            model_name='cadreport',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=18, null=True, verbose_name='خط الطول'),
        ),
    ]
