# Generated by Django 5.2.11 on 2026-02-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_reports', '0009_alter_cadreport_latitude_alter_cadreport_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadreport',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='خط العرض'),
        ),
        migrations.AlterField(
            model_name='cadreport',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='خط الطول'),
        ),
    ]
