# Generated by Django 5.2.11 on 2026-02-22 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_reports', '0011_userdevicetoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdevicetoken',
            options={},
        ),
        migrations.RemoveField(
            model_name='userdevicetoken',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userdevicetoken',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='userdevicetoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userdevicetoken',
            name='platform',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userdevicetoken',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='userdevicetoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
