# Generated by Django 5.2.11 on 2026-03-01 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_reports', '0012_alter_userdevicetoken_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CADReportActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('system', 'إجراء نظام'), ('message', 'رسالة/ملاحظة')], db_index=True, default='system', max_length=20, verbose_name='النوع')),
                ('action', models.CharField(choices=[('created', 'تم إنشاء البلاغ'), ('dispatched', 'تم ترحيل البلاغ'), ('accepted', 'تم قبول البلاغ'), ('arrived', 'تم الوصول'), ('closed', 'تم إغلاق البلاغ'), ('note', 'ملاحظة')], db_index=True, default='note', max_length=30, verbose_name='الإجراء')),
                ('message', models.TextField(blank=True, verbose_name='النص')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='وقت الإنشاء')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='cad_reports.cadreport', verbose_name='البلاغ')),
                ('user', models.ForeignKey(blank=True, help_text='قد يكون فارغًا لبعض إجراءات النظام الآلية.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cad_report_activities', to=settings.AUTH_USER_MODEL, verbose_name='المنفّذ/الكاتب')),
            ],
            options={
                'verbose_name': 'سجل بلاغ CAD',
                'verbose_name_plural': 'سجلات بلاغات CAD',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['report', 'created_at'], name='cad_reports_report__75171e_idx'), models.Index(fields=['report', 'action', 'created_at'], name='cad_reports_report__bb468c_idx')],
            },
        ),
    ]
