# Generated by Django 5.2.11 on 2026-03-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_reports', '0013_cadreportactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadreportactivity',
            name='action',
            field=models.CharField(choices=[('created', 'تم إنشاء البلاغ'), ('dispatched', 'تم ترحيل البلاغ'), ('accepted', 'تم قبول البلاغ'), ('arrived', 'تم الوصول'), ('rejected', 'تم رفض البلاغ'), ('closed', 'تم إغلاق البلاغ'), ('note', 'ملاحظة')], db_index=True, default='note', max_length=30, verbose_name='الإجراء'),
        ),
    ]
