# Generated by Django 5.2.11 on 2026-02-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='اسم الجهة')),
                ('code', models.CharField(blank=True, db_index=True, editable=False, max_length=5, unique=True, verbose_name='كود الجهة (5 أرقام)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'جهة',
                'verbose_name_plural': 'الجهات',
                'ordering': ['name'],
            },
        ),
    ]
