# Generated by Django 5.2.11 on 2026-02-14 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False, verbose_name='مفعّل')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التفعيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تفعيل البريد',
                'verbose_name_plural': 'تفعيل البريد',
            },
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(default='login', max_length=30, verbose_name='الغرض')),
                ('code_hash', models.CharField(max_length=255, verbose_name='تجزئة الكود')),
                ('expires_at', models.DateTimeField(verbose_name='ينتهي في')),
                ('max_attempts', models.PositiveIntegerField(default=5, verbose_name='الحد الأقصى للمحاولات')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='عدد المحاولات')),
                ('is_used', models.BooleanField(default=False, verbose_name='مستخدم')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستخدام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'رمز تحقق OTP',
                'verbose_name_plural': 'رموز التحقق OTP',
                'indexes': [models.Index(fields=['user', 'purpose', 'is_used'], name='accounts_em_user_id_7388a1_idx'), models.Index(fields=['expires_at'], name='accounts_em_expires_2be763_idx')],
            },
        ),
    ]
