# Generated by Django 5.2.11 on 2026-02-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location_sharing_enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='مشاركة الموقع'),
        ),
    ]
