# Generated by Django 5.2.11 on 2026-02-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_location_sharing_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='citizen_course_aed',
            field=models.BooleanField(default=False, verbose_name='دورة استخدام جهاز الصدمات (AED)'),
        ),
        migrations.AddField(
            model_name='user',
            name='citizen_course_bls',
            field=models.BooleanField(default=False, verbose_name='دورة دعم الحياة الأساسي (BLS)'),
        ),
        migrations.AddField(
            model_name='user',
            name='citizen_course_cpr',
            field=models.BooleanField(default=False, verbose_name='دورة الإنعاش القلبي الرئوي (CPR)'),
        ),
        migrations.AddField(
            model_name='user',
            name='citizen_course_first_aid_8',
            field=models.BooleanField(default=False, verbose_name='دورة الثمان الأولى للإسعافات الأولية'),
        ),
        migrations.AddField(
            model_name='user',
            name='citizen_course_life_ambassador',
            field=models.BooleanField(default=False, verbose_name='دورة سفير الحياة'),
        ),
        migrations.AddField(
            model_name='user',
            name='citizen_course_stop_bleeding',
            field=models.BooleanField(default=False, verbose_name='دورة إيقاف النزيف (Stop the Bleed)'),
        ),
        migrations.AddField(
            model_name='user',
            name='citizen_other_medical_courses',
            field=models.CharField(blank=True, default='', help_text='اكتب أسماء الدورات الأخرى إن وجدت (مفصولة بفواصل).', max_length=500, verbose_name='دورات طبية أخرى (اختياري)'),
        ),
    ]
