# Generated by Django 5.2.11 on 2026-02-28 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_citizen_course_aed_user_citizen_course_bls_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='citizen_course_aed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='citizen_course_bls',
        ),
        migrations.RemoveField(
            model_name='user',
            name='citizen_course_cpr',
        ),
        migrations.RemoveField(
            model_name='user',
            name='citizen_course_first_aid_8',
        ),
        migrations.RemoveField(
            model_name='user',
            name='citizen_course_life_ambassador',
        ),
        migrations.RemoveField(
            model_name='user',
            name='citizen_course_stop_bleeding',
        ),
        migrations.RemoveField(
            model_name='user',
            name='citizen_other_medical_courses',
        ),
    ]
