# Generated by Django 5.2.11 on 2026-03-05 17:55

import accounts.user_manager
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_citizen_course_aed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailotp',
            options={'verbose_name': 'رمز تحقق البريد', 'verbose_name_plural': 'رموز تحقق البريد'},
        ),
        migrations.AlterModelOptions(
            name='emailverification',
            options={'verbose_name': 'تحقق البريد', 'verbose_name_plural': 'تحقق البريد'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.user_manager.UserManager()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='emailotp',
            name='accounts_em_user_id_7388a1_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailotp',
            name='accounts_em_expires_2be763_idx',
        ),
        migrations.RemoveField(
            model_name='emailotp',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='emailotp',
            name='code_hash',
        ),
        migrations.RemoveField(
            model_name='emailotp',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='emailotp',
            name='max_attempts',
        ),
        migrations.RemoveField(
            model_name='emailverification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='emailverification',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='emailverification',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='code',
            field=models.CharField(db_index=True, default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailverification',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('verify_email', 'Verify Email'), ('reset_password', 'Reset Password')], max_length=32),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='used_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['user', 'purpose', 'code'], name='accounts_em_user_id_76e2eb_idx'),
        ),
    ]
