# Generated by Django 5.2.11 on 2026-03-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_citizen_health_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='citizen_health_courses',
            field=models.JSONField(blank=True, default=list, help_text='اختيار متعدد للدورات الصحية الخاصة بالمواطن.', verbose_name='دوراتي الصحية'),
        ),
        migrations.AlterField(
            model_name='user',
            name='citizen_other_health_courses',
            field=models.TextField(blank=True, default='', help_text='اكتب دورة أو أكثر عند اختيار (أخرى)، ويمكن الفصل بين الدورات بفاصلة أو سطر جديد.', verbose_name='دورات أخرى'),
        ),
    ]
