# Generated by Django 5.2.11 on 2026-03-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_citizen_health_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='الإشعارات'),
        ),
    ]
