# Generated by Django 5.2.11 on 2026-02-14 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecr_reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mobilereport',
            new_name='ecr_reports_region__aa7f57_idx',
            old_name='ecr_report_region__cfa0d3_idx',
        ),
        migrations.RenameIndex(
            model_name='mobilereport',
            new_name='ecr_reports_created_f33b07_idx',
            old_name='ecr_report_created_25f31b_idx',
        ),
    ]
