# Generated by Django 5.2.11 on 2026-02-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecr_reports', '0003_mobilereporthistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MobileReportHistory',
        ),
    ]
