# Generated by Django 5.2.11 on 2026-02-23 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecr_reports', '0004_delete_mobilereporthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilereport',
            name='blood_pressure',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='ضغط الدم'),
        ),
        migrations.AddField(
            model_name='mobilereport',
            name='blood_sugar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة السكر في الدم'),
        ),
        migrations.AddField(
            model_name='mobilereport',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='mobilereport',
            name='pulse_rate',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='معدل النبض'),
        ),
        migrations.AddField(
            model_name='mobilereport',
            name='respiratory_rate',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='معدل التنفس'),
        ),
        migrations.AddField(
            model_name='mobilereport',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='درجة الحرارة'),
        ),
    ]
