# Generated by Django 5.2.11 on 2026-02-28 23:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecr_reports', '0005_mobilereport_blood_pressure_mobilereport_blood_sugar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalconditioncatalog',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='mobilereport',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'بلاغ', 'verbose_name_plural': 'البلاغات'},
        ),
        migrations.AlterModelOptions(
            name='servicecatalog',
            options={'ordering': ['name'], 'verbose_name': 'خدمة', 'verbose_name_plural': 'الخدمات'},
        ),
        migrations.RemoveIndex(
            model_name='mobilereport',
            name='ecr_reports_region__aa7f57_idx',
        ),
        migrations.RemoveField(
            model_name='mobilereport',
            name='age',
        ),
        migrations.RemoveField(
            model_name='mobilereport',
            name='ambulance_called_by',
        ),
        migrations.RemoveField(
            model_name='mobilereport',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='mobilereport',
            name='blood_sugar',
        ),
        migrations.RemoveField(
            model_name='mobilereport',
            name='called_ambulance',
        ),
        migrations.RemoveField(
            model_name='mobilereport',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='mobilereport',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='mobilereport',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='mobilereport',
            name='patient_phone',
        ),
        migrations.RemoveField(
            model_name='mobilereport',
            name='pulse_rate',
        ),
        migrations.RemoveField(
            model_name='mobilereport',
            name='region',
        ),
        migrations.RemoveField(
            model_name='mobilereport',
            name='respiratory_rate',
        ),
        migrations.RemoveField(
            model_name='mobilereport',
            name='send_to_997',
        ),
        migrations.RemoveField(
            model_name='mobilereport',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='servicecatalog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='servicecatalog',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='medicalconditioncatalog',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='نوع الحالة'),
        ),
        migrations.AlterField(
            model_name='mobilereport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='mobilereport',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mobile_reports', to=settings.AUTH_USER_MODEL, verbose_name='المستجيب'),
        ),
        migrations.AlterField(
            model_name='mobilereport',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='خط العرض'),
        ),
        migrations.AlterField(
            model_name='mobilereport',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='خط الطول'),
        ),
        migrations.AlterField(
            model_name='mobilereport',
            name='medical_condition',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='ecr_reports.medicalconditioncatalog', verbose_name='نوع الحالة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mobilereport',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='reports', to='ecr_reports.servicecatalog', verbose_name='الخدمات المقدمة'),
        ),
        migrations.AddIndex(
            model_name='mobilereport',
            index=models.Index(fields=['medical_condition'], name='ecr_reports_medical_0c1083_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilereport',
            index=models.Index(fields=['gender'], name='ecr_reports_gender_4f0542_idx'),
        ),
    ]
