# Generated by Django 5.2.11 on 2026-02-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='كود المنطقة')),
                ('name_ar', models.CharField(max_length=100, unique=True, verbose_name='اسم المنطقة (عربي)')),
                ('name_en', models.CharField(blank=True, default='', max_length=100, verbose_name='اسم المنطقة (إنجليزي)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'منطقة',
                'verbose_name_plural': 'المناطق',
                'ordering': ['name_ar'],
            },
        ),
    ]
