# Generated by Django 5.2.11 on 2026-02-14 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
    ]

def seed_regions(apps, schema_editor):
    Region = apps.get_model("regions", "Region")

    regions = [
        {"code": "RIY", "name_ar": "منطقة الرياض", "name_en": "Riyadh"},
        {"code": "MAK", "name_ar": "منطقة مكة المكرمة", "name_en": "Makkah"},
        {"code": "MAD", "name_ar": "منطقة المدينة المنورة", "name_en": "Madinah"},
        {"code": "QAS", "name_ar": "منطقة القصيم", "name_en": "Qassim"},
        {"code": "EAS", "name_ar": "المنطقة الشرقية", "name_en": "Eastern Province"},
        {"code": "ASI", "name_ar": "منطقة عسير", "name_en": "Asir"},
        {"code": "TAB", "name_ar": "منطقة تبوك", "name_en": "Tabuk"},
        {"code": "HAI", "name_ar": "منطقة حائل", "name_en": "Hail"},
        {"code": "NBR", "name_ar": "منطقة الحدود الشمالية", "name_en": "Northern Borders"},
        {"code": "JAZ", "name_ar": "منطقة جازان", "name_en": "Jazan"},
        {"code": "NAJ", "name_ar": "منطقة نجران", "name_en": "Najran"},
        {"code": "BAH", "name_ar": "منطقة الباحة", "name_en": "Al Bahah"},
        {"code": "JWF", "name_ar": "منطقة الجوف", "name_en": "Al Jawf"},
    ]

    for r in regions:
        Region.objects.update_or_create(
            code=r["code"],
            defaults={
                "name_ar": r["name_ar"],
                "name_en": r["name_en"],
                "is_active": True,
            },
        )


def unseed_regions(apps, schema_editor):
    Region = apps.get_model("regions", "Region")
    codes = ["RIY", "MAK", "MAD", "QAS", "EAS", "ASI", "TAB", "HAI", "NBR", "JAZ", "NAJ", "BAH", "JWF"]
    Region.objects.filter(code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_regions, unseed_regions),
    ]
