# Generated by Django 5.2.11 on 2026-02-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_seed_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='center_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض (مركز المنطقة)'),
        ),
        migrations.AddField(
            model_name='region',
            name='center_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول (مركز المنطقة)'),
        ),
        migrations.AddField(
            model_name='region',
            name='default_zoom',
            field=models.PositiveSmallIntegerField(default=11, verbose_name='Zoom افتراضي للخريطة'),
        ),
    ]
