# Generated by Django 5.2.11 on 2026-02-14
from django.db import migrations


def seed_region_centers(apps, schema_editor):
    Region = apps.get_model("regions", "Region")

    # مراكز المناطق (تقريبية على المدن الرئيسية لكل منطقة)
    centers = {
        "RIY": {"lat": 24.713600, "lng": 46.675300, "zoom": 11},  # الرياض
        "MAK": {"lat": 21.389100, "lng": 39.857900, "zoom": 11},  # مكة
        "MAD": {"lat": 24.524700, "lng": 39.569200, "zoom": 11},  # المدينة
        "QAS": {"lat": 26.359200, "lng": 43.981800, "zoom": 11},  # القصيم (بريدة)
        "EAS": {"lat": 26.420700, "lng": 50.088800, "zoom": 11},  # الشرقية (الدمام)
        "ASI": {"lat": 18.216400, "lng": 42.505300, "zoom": 11},  # عسير (أبها)
        "TAB": {"lat": 28.383800, "lng": 36.566200, "zoom": 11},  # تبوك
        "HAI": {"lat": 27.530389, "lng": 41.717500, "zoom": 13},  # حائل دقيق
        "NBR": {"lat": 30.975300, "lng": 41.038100, "zoom": 11},  # الحدود الشمالية (عرعر)
        "JAZ": {"lat": 16.889200, "lng": 42.551100, "zoom": 11},  # جازان
        "NAJ": {"lat": 17.492400, "lng": 44.127700, "zoom": 11},  # نجران
        "BAH": {"lat": 20.012900, "lng": 41.467700, "zoom": 11},  # الباحة
        "JWF": {"lat": 29.969700, "lng": 40.206400, "zoom": 11},  # الجوف (سكاكا)
    }

    # حدّث الموجود فقط (بدون تخريب أي قيم تم ضبطها يدويًا)
    for code, v in centers.items():
        qs = Region.objects.filter(code=code)
        if not qs.exists():
            continue

        r = qs.first()
        # إذا فيه قيم مسبقاً لا نغيرها
        if r.center_lat is None:
            r.center_lat = v["lat"]
        if r.center_lng is None:
            r.center_lng = v["lng"]
        if getattr(r, "default_zoom", None) in (None, 0):
            r.default_zoom = v["zoom"]
        r.save(update_fields=["center_lat", "center_lng", "default_zoom"])


def unseed_region_centers(apps, schema_editor):
    Region = apps.get_model("regions", "Region")
    Region.objects.all().update(center_lat=None, center_lng=None)


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0003_region_center_lat_region_center_lng_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_region_centers, unseed_region_centers),
    ]
