# Generated by ChatGPT on 2026-02-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0004_seed_region_centers"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="boundary_geojson",
            field=models.JSONField(blank=True, help_text="اختياري. عند تعبئته يتم التحقق في API من أن الإحداثيات داخل حدود المنطقة.", null=True, verbose_name="حدود المنطقة (GeoJSON)"),
        ),
        migrations.AddField(
            model_name="region",
            name="bbox_min_lat",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name="BBox Min Lat"),
        ),
        migrations.AddField(
            model_name="region",
            name="bbox_min_lng",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name="BBox Min Lng"),
        ),
        migrations.AddField(
            model_name="region",
            name="bbox_max_lat",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name="BBox Max Lat"),
        ),
        migrations.AddField(
            model_name="region",
            name="bbox_max_lng",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name="BBox Max Lng"),
        ),
    ]
