# Generated by Django 5.2.11 on 2026-02-20 13:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='رقم التذكرة')),
                ('source', models.CharField(choices=[('WEB', 'Web'), ('MOBILE', 'Mobile')], default='WEB', max_length=10, verbose_name='المصدر')),
                ('kind', models.CharField(choices=[('INC', 'Incident'), ('REQ', 'Request')], editable=False, max_length=5, verbose_name='النوع')),
                ('category', models.CharField(choices=[('APP_OUTAGE', 'عطل في التطبيق'), ('RESPONDER_EDIT_ISSUE', 'مشكلة في تعديل بيانات مستجيب'), ('RESPONDER_DATA_MISSING', 'مشكلة عدم ظهور بيانات مستجيب'), ('SPECIFIC_REPORT_NOT_SHOWING', 'عطل في ظهور بلاغ محدد'), ('NO_ECR_CAD_INTEGRATION', 'لا يوجد تكامل في بلاغات ECR و CAD'), ('PERM_ALL_REGIONS', 'طلب صلاحية في مشاهدة جميع المناطق'), ('PERM_WEB_USER_ONE_REGION', 'طلب صلاحية يوزر ويب لمنطقة واحدة'), ('USER_DATA_CHANGE', 'طلب تعديل بيانات مستخدم')], max_length=50, verbose_name='التصنيف')),
                ('description', models.TextField(blank=True, verbose_name='وصف المشكلة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='support_tickets/%Y/%m/', verbose_name='صورة (اختياري)')),
                ('status', models.CharField(choices=[('OPEN', 'مفتوحة'), ('IN_PROGRESS', 'قيد المعالجة'), ('PAUSED', 'معلّقة (مؤقت)'), ('CLOSED', 'مغلقة')], default='OPEN', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('first_response_at', models.DateTimeField(blank=True, null=True, verbose_name='أول رد من الدعم')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإغلاق')),
                ('last_pause_reason', models.CharField(blank=True, choices=[('GENERAL_OUTAGE', 'عطل عام وجاري الحل'), ('ASK_REQUESTER', 'استفسار من صاحب الطلب'), ('HIGHER_PRIV', 'صلاحية عليا')], max_length=30, verbose_name='سبب التعليق الأخير')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='صاحب الطلب')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='نص التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعليق')),
                ('is_support_reply', models.BooleanField(default=False, verbose_name='رد دعم فني')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='support_tickets.supportticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('GENERAL_OUTAGE', 'عطل عام وجاري الحل'), ('ASK_REQUESTER', 'استفسار من صاحب الطلب'), ('HIGHER_PRIV', 'صلاحية عليا')], max_length=30, verbose_name='سبب التعليق')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='بدأ التعليق')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='انتهى التعليق')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='support_tickets.supportticket')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
