# Generated by ChatGPT on 2026-02-20

from __future__ import annotations

from datetime import timedelta

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    SupportTicket = apps.get_model("support_tickets", "SupportTicket")
    TicketMainCategory = apps.get_model("support_tickets", "TicketMainCategory")
    TicketSubCategory = apps.get_model("support_tickets", "TicketSubCategory")

    # إنشاء تصنيفين رئيسيين افتراضيين لترحيل البيانات القديمة
    main_inc, _ = TicketMainCategory.objects.get_or_create(
        kind="INC",
        name="الأعطال",
        defaults={"is_active": True, "sla_minutes": 60},
    )
    main_req, _ = TicketMainCategory.objects.get_or_create(
        kind="REQ",
        name="الطلبات",
        defaults={"is_active": True, "sla_minutes": 60},
    )

    # خريطة التصنيفات القديمة (value -> (kind, label))
    old = {
        # --- INC ---
        "APP_OUTAGE": ("INC", "عطل في التطبيق"),
        "RESPONDER_EDIT_ISSUE": ("INC", "مشكلة في تعديل بيانات مستجيب"),
        "RESPONDER_DATA_MISSING": ("INC", "مشكلة عدم ظهور بيانات مستجيب"),
        "SPECIFIC_REPORT_NOT_SHOWING": ("INC", "عطل في ظهور بلاغ محدد"),
        "NO_ECR_CAD_INTEGRATION": ("INC", "لا يوجد تكامل في بلاغات ECR و CAD"),
        # --- REQ ---
        "PERM_ALL_REGIONS": ("REQ", "طلب صلاحية في مشاهدة جميع المناطق"),
        "PERM_WEB_USER_ONE_REGION": ("REQ", "طلب صلاحية يوزر ويب لمنطقة واحدة"),
        "USER_DATA_CHANGE": ("REQ", "طلب تعديل بيانات مستخدم"),
    }

    # إنشاء الفرعيات
    sub_by_value = {}
    for value, (kind, label) in old.items():
        main = main_inc if kind == "INC" else main_req
        sub, _ = TicketSubCategory.objects.get_or_create(
            main_category_id=main.id,
            name=label,
            defaults={"is_active": True, "sla_minutes_override": None},
        )
        sub_by_value[value] = (main.id, sub.id)

    # ترحيل كل التذاكر
    for t in SupportTicket.objects.all().only("id", "category", "created_at"):
        val = getattr(t, "category", None)
        if not val or val not in sub_by_value:
            # fallback: ضعها تحت "الأعطال"
            main_id = main_inc.id
            sub, _ = TicketSubCategory.objects.get_or_create(
                main_category_id=main_inc.id,
                name="غير مصنف",
                defaults={"is_active": True, "sla_minutes_override": None},
            )
            sub_id = sub.id
        else:
            main_id, sub_id = sub_by_value[val]

        # SLA: يعتمد على الرئيسي حالياً (60) - يمكن تعديله لاحقاً من لوحة الإدارة
        sla_minutes = 60
        created_at = t.created_at
        deadline_at = created_at + timedelta(minutes=sla_minutes) if created_at else None

        SupportTicket.objects.filter(pk=t.pk).update(
            main_category_id=main_id,
            sub_category_id=sub_id,
            kind="INC" if main_id == main_inc.id else "REQ",
            sla_minutes=sla_minutes,
            deadline_at=deadline_at,
        )


def backwards(apps, schema_editor):
    # لا نرجع البيانات القديمة (category) لأننا حذفنا الحقل
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("support_tickets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketMainCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("INC", "Incident"), ("REQ", "Request")], db_index=True, max_length=5, verbose_name="نوع الكتلوج")),
                ("name", models.CharField(max_length=150, verbose_name="اسم التصنيف الرئيسي")),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّل")),
                ("sla_minutes", models.PositiveIntegerField(default=60, verbose_name="SLA (بالدقائق) للتصنيف الرئيسي")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="آخر تحديث")),
            ],
            options={
                "ordering": ["kind", "name"],
                "unique_together": {("kind", "name")},
            },
        ),
        migrations.CreateModel(
            name="TicketSubCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="اسم التصنيف الفرعي")),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّل")),
                ("sla_minutes_override", models.PositiveIntegerField(blank=True, null=True, verbose_name="SLA (بالدقائق) للفرعي (اختياري)")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="آخر تحديث")),
                ("main_category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sub_categories", to="support_tickets.ticketmaincategory", verbose_name="التصنيف الرئيسي")),
            ],
            options={
                "ordering": ["main_category__kind", "main_category__name", "name"],
                "unique_together": {("main_category", "name")},
            },
        ),
        migrations.AddField(
            model_name="supportticket",
            name="assignee",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_support_tickets", to=settings.AUTH_USER_MODEL, verbose_name="موظف الدعم الفني"),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="main_category",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="tickets", to="support_tickets.ticketmaincategory", verbose_name="تصنيف البلاغ الرئيسي"),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="sub_category",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="tickets", to="support_tickets.ticketsubcategory", verbose_name="تصنيف البلاغ الفرعي"),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="sla_minutes",
            field=models.PositiveIntegerField(default=60, verbose_name="SLA المعتمد (بالدقائق)"),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="deadline_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="موعد الاستحقاق (Deadline)"),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="kind",
            field=models.CharField(choices=[("INC", "Incident"), ("REQ", "Request")], db_index=True, editable=False, max_length=5, verbose_name="النوع"),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name="supportticket",
            name="main_category",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="tickets", to="support_tickets.ticketmaincategory", verbose_name="تصنيف البلاغ الرئيسي"),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="sub_category",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="tickets", to="support_tickets.ticketsubcategory", verbose_name="تصنيف البلاغ الفرعي"),
        ),
        migrations.RemoveField(
            model_name="supportticket",
            name="category",
        ),
    ]
