# Generated by Django 5.2.11 on 2026-02-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_tickets', '0002_catalog_sla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='kind',
            field=models.CharField(choices=[('INC', 'عطل / مشكلة'), ('REQ', 'طلب خدمة')], db_index=True, editable=False, max_length=5, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='source',
            field=models.CharField(choices=[('WEB', 'الموقع الإلكتروني'), ('MOBILE', 'تطبيق الجوال')], default='WEB', max_length=10, verbose_name='المصدر'),
        ),
        migrations.AlterField(
            model_name='ticketmaincategory',
            name='kind',
            field=models.CharField(choices=[('INC', 'عطل / مشكلة'), ('REQ', 'طلب خدمة')], db_index=True, max_length=5, verbose_name='نوع الكتلوج'),
        ),
    ]
