# Generated by Django 5.2.11 on 2026-02-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support_tickets", "0004_close_confirm_workflow"),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'مفتوحة'), ('IN_PROGRESS', 'قيد المعالجة'), ('PAUSED', 'معلّقة (مؤقت)'), ('CLOSE_REQUESTED', 'طلب إغلاق من العميل'), ('AWAITING_REQUESTER_CONFIRM', 'بانتظار تأكيد العميل'), ('CLOSED', 'مغلقة')], default='OPEN', max_length=40, verbose_name='الحالة'),
        ),
    ]
