# Generated by Django 5.2.11 on 2026-02-24 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_tickets', '0004_close_confirm_workflow'),
        ('support_tickets', '0005_alter_supportticket_status'),
    ]

    operations = [
    ]
