# Generated by Django 5.2.11 on 2026-02-24
from __future__ import annotations

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def seed_ticket_status_catalog(apps, schema_editor):
    TicketStatusCatalog = apps.get_model("support_tickets", "TicketStatusCatalog")

    # 1) Seed common baseline (keeps Arabic labels sane)
    baseline = [
        ("OPEN", "مفتوحة", False, False),
        ("IN_PROGRESS", "قيد العمل", False, False),
        ("PAUSED", "معلّقة", False, True),
        ("CLOSE_REQUESTED", "طلب إغلاق من العميل", False, False),
        ("AWAITING_REQUESTER_CONFIRM", "بانتظار تأكيد العميل", False, False),
        ("CLOSED", "مغلقة", True, False),
    ]
    for code, name, is_closed, requires_pause_reason in baseline:
        TicketStatusCatalog.objects.get_or_create(
            code=code,
            defaults={
                "name": name,
                "is_active": True,
                "requires_pause_reason": requires_pause_reason,
                "is_closed": is_closed,
                "sort_order": 10,
            },
        )

    # 2) Also seed ANY legacy statuses already stored in support tickets (defensive)
    try:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "SELECT DISTINCT status FROM support_tickets_supportticket WHERE status IS NOT NULL AND status != ''"
            )
            rows = cursor.fetchall()
        for (val,) in rows:
            code = str(val).strip()
            if not code:
                continue
            TicketStatusCatalog.objects.get_or_create(
                code=code,
                defaults={
                    "name": code,
                    "is_active": True,
                    "requires_pause_reason": (code == "PAUSED"),
                    "is_closed": (code == "CLOSED"),
                    "sort_order": 50,
                },
            )
    except Exception:
        # لا نفشل المايجريشن بسبب قراءة DB
        pass


def seed_ticket_pause_reasons(apps, schema_editor):
    TicketPauseReasonCatalog = apps.get_model("support_tickets", "TicketPauseReasonCatalog")

    name_map = {
        "GENERAL_OUTAGE": "عطل عام وجاري الحل",
        "ASK_REQUESTER": "استفسار من صاحب الطلب",
        "HIGHER_PRIV": "صلاحية عليا",
        "WAITING_USER": "بانتظار المستخدم",
        "WAITING_VENDOR": "بانتظار مزود الخدمة",
        "NEED_INFO": "نقص معلومات",
    }

    codes = set()

    # 1) Seed from legacy TicketPause.reason (CharField before this migration)
    try:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "SELECT DISTINCT reason FROM support_tickets_ticketpause WHERE reason IS NOT NULL AND reason != ''"
            )
            rows = cursor.fetchall()
        for (val,) in rows:
            if val:
                codes.add(str(val).strip())
    except Exception:
        pass

    # 2) Seed from legacy SupportTicket.last_pause_reason (CharField before removal)
    try:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "SELECT DISTINCT last_pause_reason FROM support_tickets_supportticket WHERE last_pause_reason IS NOT NULL AND last_pause_reason != ''"
            )
            rows = cursor.fetchall()
        for (val,) in rows:
            if val:
                codes.add(str(val).strip())
    except Exception:
        pass

    # 3) Ensure baseline reasons exist (to match original 0001 choices)
    codes.update(["GENERAL_OUTAGE", "ASK_REQUESTER", "HIGHER_PRIV"])

    for code in sorted(codes):
        if not code:
            continue
        TicketPauseReasonCatalog.objects.get_or_create(
            code=code,
            defaults={
                "name": name_map.get(code, code),
                "is_active": True,
                "sort_order": 10,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0005_region_boundaries"),
        ("support_tickets", "0006_merge_20260224_1331"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # =========================
        # Catalogs (PK = code where needed)
        # =========================
        migrations.CreateModel(
            name="TicketPauseReasonCatalog",
            fields=[
                ("code", models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name="الرمز")),
                ("name", models.CharField(max_length=200, unique=True, verbose_name="سبب التعليق")),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّل")),
                ("sort_order", models.PositiveIntegerField(default=100, verbose_name="ترتيب")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="آخر تحديث")),
            ],
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.RunPython(seed_ticket_pause_reasons, migrations.RunPython.noop),

        migrations.CreateModel(
            name="TicketSequence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("prefix", models.CharField(db_index=True, max_length=10, unique=True, verbose_name="البادئة")),
                ("last_number", models.PositiveIntegerField(default=0, verbose_name="آخر رقم")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="آخر تحديث")),
            ],
            options={"ordering": ["prefix"]},
        ),
        migrations.CreateModel(
            name="TicketSolutionCatalog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, unique=True, verbose_name="نوع الحل")),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّل")),
                ("sort_order", models.PositiveIntegerField(default=100, verbose_name="ترتيب")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="آخر تحديث")),
            ],
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.CreateModel(
            name="TicketStatusCatalog",
            fields=[
                ("code", models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name="الرمز")),
                ("name", models.CharField(max_length=150, verbose_name="اسم الحالة")),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّل")),
                ("requires_pause_reason", models.BooleanField(default=False, verbose_name="يتطلب سبب تعليق")),
                ("is_closed", models.BooleanField(default=False, verbose_name="مغلقة نهائياً")),
                ("sort_order", models.PositiveIntegerField(default=100, verbose_name="ترتيب")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="آخر تحديث")),
            ],
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.RunPython(seed_ticket_status_catalog, migrations.RunPython.noop),

        # =========================
        # Remove old workflow fields (from older versions)
        # =========================
        migrations.RemoveField(model_name="supportticket", name="close_requested_at"),
        migrations.RemoveField(model_name="supportticket", name="close_requested_reason"),
        migrations.RemoveField(model_name="supportticket", name="last_pause_reason"),
        migrations.RemoveField(model_name="supportticket", name="requester_decision_at"),
        migrations.RemoveField(model_name="supportticket", name="requester_reject_reason"),
        migrations.RemoveField(model_name="supportticket", name="support_closed_at"),
        migrations.RemoveField(model_name="supportticket", name="support_solution"),

        # =========================
        # Add new snapshot/assignment/solution fields
        # =========================
        migrations.AddField(
            model_name="supportticket",
            name="assigned_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="وقت الإسناد"),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="last_status_changed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="وقت تعديل الحالة"),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="support_tickets",
                to="regions.region",
                verbose_name="منطقة/مجموعة الإسناد",
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="requester_email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="البريد الإلكتروني"),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="requester_name",
            field=models.CharField(blank=True, max_length=200, verbose_name="اسم مقدم التذكرة"),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="requester_national_id",
            field=models.CharField(blank=True, max_length=50, verbose_name="رقم الهوية"),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="requester_phone",
            field=models.CharField(blank=True, max_length=50, verbose_name="رقم الجوال"),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="solution_notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات الحل"),
        ),
        migrations.AddField(
            model_name="ticketcomment",
            name="is_internal",
            field=models.BooleanField(default=False, verbose_name="تعليق داخلي"),
        ),

        # =========================
        # Alter existing fields to match new models
        # =========================
        migrations.AlterField(
            model_name="supportticket",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_support_tickets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="الإسناد (موظف الدعم الفني)",
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="وقت الإغلاق"),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="code",
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name="رقم البلاغ"),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="وقت الاستلام/الإنشاء"),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="description",
            field=models.TextField(blank=True, verbose_name="وصف المشكلة/الطلب"),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="first_response_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="وقت أول رد"),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="kind",
            field=models.CharField(
                choices=[("INC", "عطل / مشكلة"), ("REQ", "طلب خدمة")],
                db_index=True,
                editable=False,
                max_length=5,
                verbose_name="نوع البلاغ",
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="main_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets",
                to="support_tickets.ticketmaincategory",
                verbose_name="التصنيف الرئيسي",
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="support_tickets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مقدم التذكرة",
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="source",
            field=models.CharField(
                choices=[("SYSTEM", "النظام"), ("MOBILE", "تطبيق الجوال"), ("WEB", "الموقع الإلكتروني")],
                default="SYSTEM",
                max_length=10,
                verbose_name="تم الرفع عن طريق",
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="sub_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets",
                to="support_tickets.ticketsubcategory",
                verbose_name="التصنيف الفرعي",
            ),
        ),
        migrations.AlterField(
            model_name="ticketcomment",
            name="body",
            field=models.TextField(verbose_name="نص التعليق/الرد"),
        ),
        migrations.AlterField(
            model_name="ticketcomment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ ووقت الرد"),
        ),

        # =========================
        # Convert pause reason / status to FK catalogs (PK=code so legacy strings remain valid)
        # =========================
        migrations.AlterField(
            model_name="ticketpause",
            name="reason",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pauses",
                to="support_tickets.ticketpausereasoncatalog",
                verbose_name="سبب التعليق",
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="pause_reason",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets",
                to="support_tickets.ticketpausereasoncatalog",
                verbose_name="سبب التعليق",
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="solution_catalog",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets",
                to="support_tickets.ticketsolutioncatalog",
                verbose_name="نوع الحل (كتلوج)",
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets",
                to="support_tickets.ticketstatuscatalog",
                verbose_name="حالة التذكرة",
            ),
        ),

        # =========================
        # Status log
        # =========================
        migrations.CreateModel(
            name="TicketStatusLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="وقت التغيير")),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ticket_status_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم التغيير بواسطة",
                    ),
                ),
                (
                    "from_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="from_logs",
                        to="support_tickets.ticketstatuscatalog",
                        verbose_name="من حالة",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="support_tickets.supportticket",
                    ),
                ),
                (
                    "to_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="to_logs",
                        to="support_tickets.ticketstatuscatalog",
                        verbose_name="إلى حالة",
                    ),
                ),
            ],
            options={"ordering": ["-changed_at"]},
        ),
    ]
