# Generated by Django 5.2.11 on 2026-02-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_tickets', '0007_ticketpausereasoncatalog_ticketsequence_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'تذكرة دعم فني', 'verbose_name_plural': 'تذاكر الدعم الفني'},
        ),
        migrations.AlterModelOptions(
            name='ticketcomment',
            options={'ordering': ['created_at'], 'verbose_name': 'تعليق على تذكرة', 'verbose_name_plural': 'تعليقات التذاكر'},
        ),
        migrations.AlterModelOptions(
            name='ticketmaincategory',
            options={'ordering': ['kind', 'name'], 'verbose_name': 'تصنيف رئيسي', 'verbose_name_plural': 'التصنيفات الرئيسية'},
        ),
        migrations.AlterModelOptions(
            name='ticketpause',
            options={'ordering': ['-started_at'], 'verbose_name': 'تعليق تذكرة', 'verbose_name_plural': 'تعليقات التذاكر (إيقاف مؤقت)'},
        ),
        migrations.AlterModelOptions(
            name='ticketpausereasoncatalog',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'سبب تعليق', 'verbose_name_plural': 'كتلوج أسباب تعليق التذكرة'},
        ),
        migrations.AlterModelOptions(
            name='ticketsequence',
            options={'ordering': ['prefix'], 'verbose_name': 'تسلسل التذاكر', 'verbose_name_plural': 'تسلسلات أرقام التذاكر'},
        ),
        migrations.AlterModelOptions(
            name='ticketsolutioncatalog',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'حل', 'verbose_name_plural': 'كتلوج الحلول'},
        ),
        migrations.AlterModelOptions(
            name='ticketstatuscatalog',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'حالة تذكرة', 'verbose_name_plural': 'كتلوج حالات التذاكر'},
        ),
        migrations.AlterModelOptions(
            name='ticketstatuslog',
            options={'ordering': ['-changed_at'], 'verbose_name': 'سجل حالة التذكرة', 'verbose_name_plural': 'سجلات حالات التذاكر'},
        ),
        migrations.AlterModelOptions(
            name='ticketsubcategory',
            options={'ordering': ['main_category__kind', 'main_category__name', 'name'], 'verbose_name': 'تصنيف فرعي', 'verbose_name_plural': 'التصنيفات الفرعية'},
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='source',
            field=models.CharField(choices=[('SYSTEM', 'النظام'), ('MOBILE', 'تطبيق الجوال')], default='SYSTEM', max_length=10, verbose_name='تم الرفع عن طريق'),
        ),
    ]
